server:
  address: 0.0.0.0
  port: 8085
eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.112:8762/eureka  
spring: 
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/houses?useUnicode=true&characterEncoding=UTF-8&useSSL=FALSE&serverTimezone=Hongkong
    username: root
    password: 991226   
